################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ChibiOS_3.0.5/ext/stdperiph_stm32f4/src \
ChibiOS_3.0.5/os/common/ports/ARM/compilers/GCC \
ChibiOS_3.0.5/os/common/ports/ARMCMx/compilers/GCC \
ChibiOS_3.0.5/os/common/ports/ARMCMx/compilers/IAR \
ChibiOS_3.0.5/os/common/ports/ARMCMx/compilers/RVCT \
ChibiOS_3.0.5/os/common/ports/e200/compilers/GCC \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC560BCxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC560Bxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC560Dxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC560Pxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC563Mxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC564Axx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC56ECxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC56ELxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC57EMxx_HSM \
ChibiOS_3.0.5/os/hal/lib/streams \
ChibiOS_3.0.5/os/hal/osal/nil \
ChibiOS_3.0.5/os/hal/osal/os-less/ARMCMx \
ChibiOS_3.0.5/os/hal/osal/rt \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/DACv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/DMAv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/GPIOv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/GPIOv2 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/I2Cv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/I2Cv2 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/OTGv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/RTCv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/RTCv2 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/SPIv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/SPIv2 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/TIMv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/USARTv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/USARTv2 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/USBv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32F0xx \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32F1xx \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32F37x \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32F3xx \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32F4xx \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32L1xx \
ChibiOS_3.0.5/os/hal/ports/common/ARMCMx \
ChibiOS_3.0.5/os/hal/src \
ChibiOS_3.0.5/os/nil/ports/ARMCMx/compilers/GCC \
ChibiOS_3.0.5/os/nil/ports/ARMCMx \
ChibiOS_3.0.5/os/nil/ports/AVR \
ChibiOS_3.0.5/os/nil/ports/e200/compilers/GCC \
ChibiOS_3.0.5/os/nil/ports/e200 \
ChibiOS_3.0.5/os/nil/src \
ChibiOS_3.0.5/os/nil/templates \
ChibiOS_3.0.5/os/rt/ports/ARM \
ChibiOS_3.0.5/os/rt/ports/ARM/compilers/GCC \
ChibiOS_3.0.5/os/rt/ports/ARMCMx \
ChibiOS_3.0.5/os/rt/ports/ARMCMx/cmsis_os \
ChibiOS_3.0.5/os/rt/ports/ARMCMx/compilers/GCC \
ChibiOS_3.0.5/os/rt/ports/ARMCMx/compilers/IAR \
ChibiOS_3.0.5/os/rt/ports/ARMCMx/compilers/RVCT \
ChibiOS_3.0.5/os/rt/ports/AVR \
ChibiOS_3.0.5/os/rt/ports/SIMIA32 \
ChibiOS_3.0.5/os/rt/ports/e200 \
ChibiOS_3.0.5/os/rt/ports/e200/compilers/GCC \
ChibiOS_3.0.5/os/rt/src \
ChibiOS_3.0.5/os/rt/templates \
ChibiOS_3.0.5/os/rt/templates/meta \
ChibiOS_3.0.5/os/various/cpp_wrappers \
ChibiOS_3.0.5/os/various/devices_lib/accel \
ChibiOS_3.0.5/os/various/devices_lib/lcd \
ChibiOS_3.0.5/os/various \
ChibiOS_3.0.5/os/various/fatfs_bindings \
ChibiOS_3.0.5/os/various/lwip_bindings/arch \
ChibiOS_3.0.5/os/various/lwip_bindings \
applications \
applications/er \
applications/finn \
blackmagic \
blackmagic/target \
blackmagic/target/flashstub \
. \
build/100_250/obj \
build/100_250_mkiii/obj \
build/100_250_mkiii_no_limits/obj \
build/100_250_no_limits/obj \
build/100_500/obj \
build/100_500_no_limits/obj \
build/140_300/obj \
build/40/obj \
build/410/obj \
build/410_0005ohm/obj \
build/410_005ohm/obj \
build/410_no_limits/obj \
build/45/obj \
build/46/obj \
build/46_0005ohm/obj \
build/46_33k/obj \
build/48/obj \
build/49/obj \
build/60/obj \
build/60_75/obj \
build/60_75_mk2/obj \
build/60_75_mk2_no_limits/obj \
build/60_75_no_limits/obj \
build/60_mk3/obj \
build/60_mk3_no_limits/obj \
build/60_mk4/obj \
build/60_mk4_no_limits/obj \
build/60_mk5/obj \
build/60_mk5_no_limits/obj \
build/60_mk6/obj \
build/60_mk6_hp/obj \
build/60_mk6_hp_no_limits/obj \
build/60_mk6_max/obj \
build/60_mk6_no_limits/obj \
build/60_no_limits/obj \
build/60v2_alva/obj \
build/60v2_alva_mk1/obj \
build/60v2_alva_mk2/obj \
build/75_100/obj \
build/75_100_V2/obj \
build/75_100_V2_0005ohm/obj \
build/75_100_V2_005ohm/obj \
build/75_100_V2_no_limits/obj \
build/75_100_no_limits/obj \
build/75_300/obj \
build/75_300_mkiv/obj \
build/75_300_mkiv_no_limits/obj \
build/75_300_no_limits/obj \
build/75_300_r2/obj \
build/75_300_r2_no_limits/obj \
build/75_300_r3/obj \
build/75_300_r3_no_limits/obj \
build/75_600/obj \
build/75_600_no_limits/obj \
build/Cheap_FOCer_2/obj \
build/Cheap_FOCer_2_V09/obj \
build/Cheap_FOCer_2_V09_no_limits/obj \
build/Cheap_FOCer_2_no_limits/obj \
build/Little_FOCer/obj \
build/Little_FOCer_V3/obj \
build/Little_FOCer_V3_1/obj \
build/a200s_v2.1/obj \
build/a200s_v2.2/obj \
build/a200s_v3/obj \
build/a200s_v4/obj \
build/a50s_v22_12s/obj \
build/a50s_v22_12s_hg/obj \
build/a50s_v22_6s/obj \
build/a50s_v22_6s_hg/obj \
build/a50s_v23_12s/obj \
build/a50s_v23_20s/obj \
build/a50s_v23_6s/obj \
build/a50s_v23_8s/obj \
build/axiom/obj \
build/das_mini/obj \
build/das_rs/obj \
build/edu/obj \
build/edu_no_limits/obj \
build/es19/obj \
build/fsesc_75_200_alu/obj \
build/fsesc_75_200_alu_no_limits/obj \
build/fsesc_75_300/obj \
build/gesc/obj \
build/go_foc_dv6_pro/obj \
build/go_foc_dv6_pro_no_limits/obj \
build/go_foc_g300/obj \
build/go_foc_g300_no_limits/obj \
build/go_foc_hi200/obj \
build/go_foc_hi200_no_limits/obj \
build/go_foc_hv200/obj \
build/go_foc_hv200_no_limits/obj \
build/go_foc_m100/obj \
build/go_foc_m100_no_limits/obj \
build/gp/obj \
build/hd60/obj \
build/hd60_no_limits/obj \
build/hd75/obj \
build/hd75_no_limits/obj \
build/ka160/obj \
build/luna_bbshd/obj \
build/luna_m600/obj \
build/luna_m600_Rev5/obj \
build/mbot/obj \
build/mini4/obj \
build/r2/obj \
build/raiden7/obj \
build/rd2/obj \
build/resc/obj \
build/rh/obj \
build/solo/obj \
build/solo_no_limits/obj \
build/spesc/obj \
build/stormcore_100d/obj \
build/stormcore_100d_no_limits/obj \
build/stormcore_100d_parallel/obj \
build/stormcore_100d_v2/obj \
build/stormcore_100d_v2_no_limits/obj \
build/stormcore_100dx/obj \
build/stormcore_100dx_no_limits/obj \
build/stormcore_100dx_parallel/obj \
build/stormcore_100s/obj \
build/stormcore_100s_no_limits/obj \
build/stormcore_60d/obj \
build/stormcore_60d+/obj \
build/stormcore_60d+_no_limits/obj \
build/stormcore_60d_no_limits/obj \
build/stormcore_60dxs/obj \
build/stormcore_60dxs_no_limits/obj \
build/uavc_omega/obj \
build/uavc_qcube/obj \
build/ubox_single_100/obj \
build/ubox_single_75/obj \
build/ubox_single_75_no_limits/obj \
build/ubox_single_80/obj \
build/ubox_single_80_no_limits/obj \
build/ubox_single_85_200/obj \
build/ubox_single_85_200_no_limits/obj \
build/ubox_v1_75_micro/obj \
build/ubox_v1_75_micro_no_limits/obj \
build/ubox_v1_75_typec/obj \
build/ubox_v1_75_typec_no_limits/obj \
build/ubox_v2_100/obj \
build/ubox_v2_100_no_limits/obj \
build/ubox_v2_75/obj \
build/ubox_v2_75_no_limits/obj \
build/unity/obj \
build/unity_no_limits/obj \
build/uxv_sr/obj \
build/warrior6/obj \
comm \
driver \
driver/lora \
driver/nrf \
encoder \
hwconf/Ubox/100v \
hwconf/Ubox/75v \
hwconf \
hwconf/flipsky \
hwconf/ipm/ka160 \
hwconf/luna/bbshd \
hwconf/luna/m600 \
hwconf/makerx \
hwconf/other \
hwconf/other/vesc4 \
hwconf/shaman/Cheap_FOCer_2 \
hwconf/shaman/Little_FOCer \
hwconf/shaman \
hwconf/stormcore/100D \
hwconf/stormcore/100S \
hwconf/stormcore/60D \
hwconf/teamtriforceuk/a200s_v2 \
hwconf/teamtriforceuk/a200s_v3 \
hwconf/teamtriforceuk/a200s_v4 \
hwconf/teamtriforceuk/a50s_v22 \
hwconf/teamtriforceuk/a50s_v23 \
hwconf/trampa/100_250 \
hwconf/trampa/100_250_MKIII \
hwconf/trampa/100_500 \
hwconf/trampa/140_300 \
hwconf/trampa/60_75 \
hwconf/trampa/60_alva \
hwconf/trampa/75_300 \
hwconf/trampa/75_300_MKIV \
hwconf/trampa/hd \
hwconf/trampa/vesc6 \
hwconf/trampa/vesc_edu \
hwconf/trampa/vesc_gp \
imu/BMI160_driver \
imu/Fusion/Examples \
imu/Fusion \
imu \
libcanard \
libcanard/dsdl/uavcan/equipment/esc \
libcanard/dsdl/uavcan/equipment/power \
libcanard/dsdl/uavcan/protocol/file \
libcanard/dsdl/uavcan/protocol/param \
libcanard/dsdl/uavcan/protocol \
libcanard/dsdl/vesc \
lispBM/c_libs/examples/config \
lispBM/c_libs/examples/config/conf \
lispBM/c_libs/examples/custom_data_comm \
lispBM/c_libs/examples/extension \
lispBM/c_libs/examples/speed_test \
lispBM/c_libs/examples/ssd1306 \
lispBM/c_libs/examples/thread \
lispBM/c_libs/examples/ws2812 \
lispBM/c_libs/stdperiph_stm32f4/src \
lispBM/c_libs/utils \
lispBM/lispBM/benchmarks/bench_chibi \
lispBM/lispBM/chibios-examples/repl-ChibiOS \
lispBM/lispBM/chibios-examples/xmas_dac \
lispBM/lispBM/esp-examples/repl/main \
lispBM/lispBM/examples \
lispBM/lispBM/old/repl-cps-zynq \
lispBM/lispBM/old/repl-ec \
lispBM/lispBM/old/repl-esp-idf/main \
lispBM/lispBM/platform/chibios/src \
lispBM/lispBM/platform/freertos/src \
lispBM/lispBM/platform/linux/src \
lispBM/lispBM/platform/zephyr/src \
lispBM/lispBM/repl \
lispBM/lispBM/sdlrepl \
lispBM/lispBM/src \
lispBM/lispBM/src/extensions \
lispBM/lispBM/src/visual \
lispBM/lispBM/tests \
lispBM/lispBM/zephyr-examples/repl-zephyr/src \
lispBM/lispBM/zephyr-examples/repl-zephyr \
lispBM \
motor \
qmlui/app \
qmlui/hw \
qmlui \
tests/angles \
tests/float_serialization \
tests/packet_recovery \
tests/utils_math \
tools/Qt/5.15.2/msvc2019_64/mkspecs/devices/linux-arm-amlogic-8726M-g++ \
tools/Qt/5.15.2/msvc2019_64/mkspecs/devices/linux-mipsel-broadcom-97425-g++ \
tools/Qt/5.15.2/msvc2019_64/mkspecs/features/data \
tools/Qt/Tools/QtCreator/share/qtcreator/cplusplus/examples \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/app-and-lib/app \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/app-and-lib/lib \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/at90can128olimex/redblink \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/cc2540usbdongle/greenblink \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/cy7c68013a/nes-gamepads \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/esp8266/access-point \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/nes-gamepads \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/msp430f5529/redblink \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/gcc \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/iar \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10001/greenblink/keil \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/gcc \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/iar \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/pca10040/greenblink/keil \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/gcc \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/iar \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f103/greenblink/keil \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/gcc \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/iar \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/stm32f4discovery/blueblink/keil \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/baremetal/stm8s103f3/redblink \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/capnproto/addressbook_cpp \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/capnproto/calculator_cpp \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/code-generator \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/collidingmice \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/compiled-qml \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/grpc \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/helloworld-complex/src \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/helloworld-minimal \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/helloworld-qt \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/install-bundle \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/pkgconfig-provider \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/protobuf/addressbook_cpp \
tools/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/examples/rpaths \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/commands \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/container \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/instances \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/interfaces \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/qml2puppet/editor3d/qt5compat \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/qml2puppet/iconrenderer \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/qml2puppet/import3d \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/qml2puppet/instances \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/qml2puppet \
tools/Qt/Tools/QtCreator/share/qtcreator/qml/qmlpuppet/qmlprivategate \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/qt4project/customwidgetwizard \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/autotest/files \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/classes/cpp \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/classes/itemmodel \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/codesnippet \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/files/cppsource \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/projects/consoleapp \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/projects/cpplibrary \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/projects/plainc \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/projects/plaincpp \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/projects/qtquick2-extension/example \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/projects/qtquick2-extension \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/projects/qtquickapplication \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/projects/qtwidgetsapplication \
tools/Qt/Tools/QtCreator/share/qtcreator/templates/wizards/qtcreatorplugin \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v6-m/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v6-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/softfp/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-m/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/softfp/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/softfp/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.base/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.base \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/softfp/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/softfp/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1 \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v6-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-ar \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-ar/fpv3/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-ar/fpv3/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv4-sp/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv4-sp/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv5/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv5/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.base \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5-sp/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5-sp/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/cpp \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/fpin \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/fpout \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/minimum \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/multiram \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/qemu \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/retarget \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/semihost \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/startup \
util \
util/lzo \

